### ISSUE TITLE
Faster diff or ability to disable it in the classic reporter

### ISSUE THREAD

**Issue by mourner** [isaacs/tap-mocha-reporter#8]
When Tap compares relatively big objects and fails, outputting a diff can take a crazy amount of time, sometimes freezing Tap completely (e.g. when comparing buffers of files that take more than several megabytes).

Options I see here:

- Heuristic that automatically disables diff when comparing big objects
- Finding out why diff is so slow and making it faster
- Ability to disable diff in the classic reporter completely
- Even better, ability to disable diff per assertion

**Comment by isaacs** [comment]
Since the diffing only happens later, and only operates on strings, I'd suspect that the problem is actually generating the *tap* output, not the pretty diff.  That being said, wouldn't be hard to implement any of these.

Do you have a simple test case that is painfully slow?

Is this still a problem with the last few tap releases?  The deep equality checking was all refactored a few months ago.
